---
title: "tidy tuesday 3"
---

```{r}
library(tidyverse)


install.packages("tidytuesdayR")
tuesdata <- tidytuesdayR::tt_load('2023-01-24')
tuesdata <- tidytuesdayR::tt_load(2023, week = 4)

alone <- tuesdata$alone

survivalists <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-01-24/survivalists.csv')
loadouts <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-01-24/loadouts.csv')
episodes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-01-24/episodes.csv')
seasons <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-01-24/seasons.csv')


```


```{r}

library(tidyverse)
 
df <- expand_grid(
  days_lasted = 0:max(survivalists$days_lasted),
  gender = unique(survivalists$gender)
) |> 
  left_join(
    survivalists |> 
      count(days_lasted, gender),
    by = c("days_lasted", "gender")
  ) |> 
  left_join(
    survivalists |> 
      count(gender, name = "N"),
    by = "gender"
  ) |> 
  group_by(gender) |> 
  mutate(
    n = replace_na(n, 0),
    n_lasted = N-cumsum(n),
    p = n_lasted/N
  ) 
 
# Kaplan-Meier survival curves
# code is simplified and plot won't match below
df |> 
  ggplot(aes(days_lasted, p, colour = gender)) +
  geom_line() 
 


```


```{r}
library(forcats)
 
loadouts |>
  count(item) |>
  mutate(item = fct_reorder(item, n, max)) |>
  ggplot(aes(item, n)) +
  geom_col() +
  geom_text(aes(item, n + 3, label = n), size = 3) +
  coord_flip()

```


```{r}
#create scatterplot
ggplot(data = episodes, 
                mapping = aes(x = season, 
                              y = episode_number_overall
                              )) +
  geom_point(alpha = 0.5) +
  labs(x = "season",
       y = "episode number overall",
       title = "season by episode number overall")

```


