---
title: "week 5"
---

# Load libraries

```{r}
library(tidyverse)     # includes readr & tibble
library(rio)           # for almost any data import/export
library(haven)         # for SPSS, Stata,and SAS files
library(readxl)        # for Excel files
library(googlesheets4) # for Google Sheets
```

# Options for viewing data

```{r}
data(cars) # make data from R package available in global environment
#View(cars) # view in editor pane
#print(cars) # print to console
#cars # print to console

# show columns as rows
glimpse(cars)

#show first 10 lines of table
head(cars)

# print nicely to web
knitr::kable(head(cars))

```


# Produce summaries

```{r}
summary(cars)
```

```{r}
library(summarytools)
#view(dfSummary(starwars))

```

# Importing data

```{r}
library(rio)

demo_tsv <- import(file = "demo.tsv")

glimpse(demo_tsv)

demo_tsv$factor <- as.factor(demo_tsv$factor)

glimpse(demo_tsv)

demo_tsv$
demo_tsv$factor

```

```{r}
demo_tsv  <- import("demo.tsv")  # tab-separated values
demo_csv  <- import("demo.csv")  # comma-separated values
demo_xls  <- import("demo.xlsx") # Excel format
demo_sav  <- import("demo.sav")  # SPSS format
```

```{r}
gs4_deauth() # skip authorisation for public data

demo_gs4  <- googlesheets4::read_sheet(
  ss = "16dkq0YL0J7fyAwT1pdgj1bNNrheckAU_2-DKuuM6aGI"
)

gs4_get(ss = "16dkq0YL0J7fyAwT1pdgj1bNNrheckAU_2-DKuuM6aGI")
```

```{r}
demo <- readr::read_csv("demo.csv")

spec(demo)

corrected_cols <- cols(
  character = col_character(),
  factor = col_factor(levels = c("low", "med", "high")),
  integer = col_integer(),
  double = col_double(),
  logical = col_logical(),
  date = col_date(format = "%Y-%m-%d")
)

demo <- readr::read_csv("demo.csv", col_types = corrected_cols)

glimpse(demo)

```


# Write your own data

```{r}

avatar <- tibble(
  name = c("Katara", "Toph", "Sokka"),
  bends = c("water", "earth", NA),
  friendly = TRUE,
  numbers = c(1,2,3),
  more_numbers = 1:3,
  even_more = seq(1,3,1)
)

# print it
avatar
```


```{r}
avatar_by_row <- tribble(
  ~name,    ~bends,  ~friendly, ~numbers,
  "Katara", "water", TRUE, 1L,
  "Toph",   "earth", TRUE, 2L,
  "Sokka",  NA,      TRUE, 3L
)
avatar_by_row
```

# Export data

```{r}
export(avatar, "avatar.csv")
```


